<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aee4a86e-68bc-4d7f-ae41-6f686adba274</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ComandaFlow.Application\ComandaFlow.Application.csproj" />
    <ProjectReference Include="..\ComandaFlow.Infrastructure\ComandaFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
